{% set version = "2024.5a12" %}

package:
  name: cctbx-base
  version: {{ version }}

source:
  url: https://artprodcus3.artifacts.visualstudio.com/Ae7d56bcd-6398-4fef-808d-577536b26a95/67feccdf-8c7f-4afe-8ff5-f21e77cdbf9d/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2NjdGJ4LXJlbGVhc2UvcHJvamVjdElkLzY3ZmVjY2RmLThjN2YtNGFmZS04ZmY1LWYyMWU3N2NkYmY5ZC9idWlsZElkLzEyMTA3L2FydGlmYWN0TmFtZS9jY3RieC0yMDI0LjVhMTI1/content?format=file&subPath=%2Fcctbx-{{ version }}.tar.gz  # [unix]
  url: https://artprodcus3.artifacts.visualstudio.com/Ae7d56bcd-6398-4fef-808d-577536b26a95/67feccdf-8c7f-4afe-8ff5-f21e77cdbf9d/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2NjdGJ4LXJlbGVhc2UvcHJvamVjdElkLzY3ZmVjY2RmLThjN2YtNGFmZS04ZmY1LWYyMWU3N2NkYmY5ZC9idWlsZElkLzEyMTA3L2FydGlmYWN0TmFtZS9jY3RieC0yMDI0LjVhMTI1/content?format=file&subPath=/cctbx-{{ version }}.tar.gz  # [win]
  patches:
    - cbf.patch
    - dxtbx.patch
    - libann.patch
    - libtbx_osx-arm64.patch  # [build_platform != target_platform]
    - libtbx_SConscript.patch

build:
  number: 0
  preserve_egg_dir: true

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - boost =1.78             # [py<38]
    - boost-cpp =1.78         # [py<38]
    - libboost-python-devel   # [py>37]
    - libboost-devel          # [py>37]
    - eigen
    - future
    - libglu  # [linux]
    - libxcrypt  # [linux and py==37]
    - numpy
    - pip
    - python
    - python.app  # [osx]
    - scons
    - setuptools =69.0  # [py==37]
    - setuptools
    - six
    - wheel =0.42  # [py==37]
    - xorg-libxfixes  # [linux]

outputs:
  - name: cctbx-base
    requirements:
      run:
        - boost =1.78             # [py<38]
        - boost-cpp =1.78         # [py<38]
        - biopython
        - future
        - {{ pin_compatible('libglu') }}  # [linux]
        - libsvm
        - matplotlib-base
        - mrcfile
        - {{ pin_compatible('numpy') }}
        - pillow
        - psutil
        - python
        - python.app  # [osx]
        - reportlab
        - requests
        - scipy
        - six
    test:
      imports:
        - scitbx.array_family.flex
        - gltbx.gl  # [not (win and py>=38)]
        - gltbx.glu  # [not (win and py>=38)]
      commands:
        - libtbx.show_commands
        - pip check
      requires:
        - pip

  - name: cctbx
    build:
    requirements:
      host:
        - python
      run:
        - {{ pin_subpackage('cctbx-base', max_pin="x.x.x") }}
        - ipython
        - pyside2  # [(x86_64 or arm64) and py<312]
        - pyopengl  # [win]
        - python
        - pyzmq
        - qt-webengine  # [(x86_64 or arm64) and py<312]
        - websockets
        - wxpython  # [(x86_64 or arm64) and py<312]
    test:
      imports:
        - scitbx.array_family.flex
        - gltbx.gl  # [not (win and py>=38)]
        - gltbx.glu  # [not (win and py>=38)]
      commands:
        - libtbx.show_commands
        - pip check
        - libtbx.python -c "import wx; wx.App()"  # [not linux and py<312]
      requires:
        - pip

about:
  home: https://github.com/cctbx/cctbx_project
  license: BSD-3-Clause-LBNL AND BSD-3-Clause AND BSL-1.0 AND LGPL-2.0-only AND LGPL-2.1-only AND LGPL-3.0-only AND MIT AND LGPL-2.0-or-later WITH WxWindows-exception-3.1
  license_family: Other
  license_file:
    - ./licenses/LICENSE.txt
    - ./licenses/Boost_LICENSE_1_0.txt
    - ./licenses/bsd_3_clause.txt
    - ./licenses/gpl-3.0.txt
    - ./licenses/lgpl-2.0.txt
    - ./licenses/lgpl-2.1.txt
    - ./licenses/lgpl-3.0.txt
    - ./licenses/mit.txt
    - ./licenses/wxWindows_3.1.txt

  summary: The Computational Crystallography Toolbox
  description: |
    The Computational Crystallography Toolbox (cctbx) is being developed
    as the open source component of the Phenix system. The goal of the
    Phenix project is to advance automation of macromolecular structure
    determination. Phenix depends on the cctbx, but not vice versa. This
    hierarchical approach enforces a clean design as a reusable library.
    The cctbx is therefore also useful for small-molecule crystallography
    and even general scientific applications.
  doc_url: https://cctbx.github.io/
  dev_url: https://github.com/cctbx/cctbx_project

extra:
  recipe-maintainers:
    - bkpoon
    - phyy-nx
